---
global:
  pattern: rag-llm-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
# Possible value for db.type = [REDIS, PGVECTOR]
  db:
    index: docs
    type: REDIS
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
